# Generated by Django 4.2.3 on 2023-07-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
