# Generated by Django 4.2.3 on 2023-07-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_rename_image_url_games_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='max_level',
            new_name='maxlevel',
        ),
    ]
