# Generated by Django 4.2.3 on 2023-07-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_rename_max_level_games_maxlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='maxlevel',
            new_name='maxLevel',
        ),
    ]
