# Generated by Django 4.2.3 on 2023-07-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0005_usergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
