# Generated by Django 4.2.3 on 2023-07-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0007_usergame_usergame_alter_usergame_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGame',
        ),
    ]
